/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sudoku;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import java.util.GregorianCalendar;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sun.audio.*;

/**
 *
 * @author Даулет
 */
public class Frame extends javax.swing.JFrame {
     
      private Sudoku sudocu=new Sudoku();
      private int[][]s1;  
      private int timecount=0;
      private int timecnt=0;
      private boolean istimerrun;
      private java.util.Timer timer=new Timer();
      private TimerTask timeCount=new MyTimerTask();
      private JTextField[][] tm1;   
      private TimeConverter tk=new TimeConverter();
      private File file;
      private String difficulty;
      private AudioPlayer MGP = AudioPlayer.player;
      private AudioStream BGM;
      private AudioData MD;
      private int proverka=0;
            
    /**
     * Creates new form Frame
     */
      
          
    public Frame() {
          
        initComponents();
        super.setLocationRelativeTo(null);
        butRasklad.grabFocus();
        jPanel1.setBackground(Color.green);
        this.setIconImage(new ImageIcon("sudoku.png").getImage());
        
        for (int i=0;i<9;i++){
            for (int j=0;j<9;j++){
                tm1[i][j].addKeyListener(new MyKeyAdapter(tm1[i][j]));
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jDifficulty = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        t00 = new javax.swing.JTextField();
        t02 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t01 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        t03 = new javax.swing.JTextField();
        t04 = new javax.swing.JTextField();
        t05 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t23 = new javax.swing.JTextField();
        t24 = new javax.swing.JTextField();
        t25 = new javax.swing.JTextField();
        t07 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t26 = new javax.swing.JTextField();
        t27 = new javax.swing.JTextField();
        t08 = new javax.swing.JTextField();
        t06 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t28 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t42 = new javax.swing.JTextField();
        t51 = new javax.swing.JTextField();
        t40 = new javax.swing.JTextField();
        t50 = new javax.swing.JTextField();
        t41 = new javax.swing.JTextField();
        t30 = new javax.swing.JTextField();
        t31 = new javax.swing.JTextField();
        t32 = new javax.swing.JTextField();
        t52 = new javax.swing.JTextField();
        t34 = new javax.swing.JTextField();
        t35 = new javax.swing.JTextField();
        t33 = new javax.swing.JTextField();
        t43 = new javax.swing.JTextField();
        t44 = new javax.swing.JTextField();
        t45 = new javax.swing.JTextField();
        t53 = new javax.swing.JTextField();
        t54 = new javax.swing.JTextField();
        t55 = new javax.swing.JTextField();
        t37 = new javax.swing.JTextField();
        t48 = new javax.swing.JTextField();
        t57 = new javax.swing.JTextField();
        t58 = new javax.swing.JTextField();
        t38 = new javax.swing.JTextField();
        t36 = new javax.swing.JTextField();
        t46 = new javax.swing.JTextField();
        t56 = new javax.swing.JTextField();
        t47 = new javax.swing.JTextField();
        t60 = new javax.swing.JTextField();
        t62 = new javax.swing.JTextField();
        t70 = new javax.swing.JTextField();
        t61 = new javax.swing.JTextField();
        t71 = new javax.swing.JTextField();
        t72 = new javax.swing.JTextField();
        t80 = new javax.swing.JTextField();
        t81 = new javax.swing.JTextField();
        t82 = new javax.swing.JTextField();
        t63 = new javax.swing.JTextField();
        t64 = new javax.swing.JTextField();
        t65 = new javax.swing.JTextField();
        t73 = new javax.swing.JTextField();
        t74 = new javax.swing.JTextField();
        t75 = new javax.swing.JTextField();
        t83 = new javax.swing.JTextField();
        t84 = new javax.swing.JTextField();
        t85 = new javax.swing.JTextField();
        t67 = new javax.swing.JTextField();
        t78 = new javax.swing.JTextField();
        t87 = new javax.swing.JTextField();
        t88 = new javax.swing.JTextField();
        t68 = new javax.swing.JTextField();
        t66 = new javax.swing.JTextField();
        t76 = new javax.swing.JTextField();
        t86 = new javax.swing.JTextField();
        t77 = new javax.swing.JTextField();
        butRasklad = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSound = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jFrame1.setTitle("Доска почета");
        jFrame1.setMinimumSize(new java.awt.Dimension(570, 225));
        jFrame1.setResizable(false);

        jDifficulty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ученик", "Банзай", "Сенсэй", "Самурай", "Камикадзе" }));
        jDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDifficultyActionPerformed(evt);
            }
        });

        jButton2.setText("Закрыть");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jText.setEditable(false);
        jText.setColumns(20);
        jText.setRows(5);
        jScrollPane1.setViewportView(jText);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Судоку");
        setResizable(false);

        t00.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t00.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t02.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t01.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t03.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t03.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t04.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t04.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t05.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t05.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t07.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t07.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t08.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t08.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t06.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t06.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t42.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t51.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t51.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t40.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t50.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t41.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t32.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t52.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t34.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t35.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t43.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t45.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t53.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t54.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t55.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t37.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t48.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t57.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t58.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t38.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t36.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t46.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t56.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t47.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t60.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t62.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t70.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t61.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t71.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t72.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t72.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t80.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t80.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t81.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t81.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t82.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t82.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t63.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t64.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t65.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t65.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t73.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t74.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t75.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t75.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t83.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t83.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t84.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t84.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t85.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t85.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t67.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t67.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t78.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t87.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t87.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t88.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t88.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t68.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t68.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t66.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t66.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t76.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t76.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t86.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t86.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t77.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t77.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        butRasklad.setText("Новый расклад");
        butRasklad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRaskladListener(evt);
            }
        });

        jSlider1.setMaximum(63);
        jSlider1.setMinimum(27);
        jSlider1.setMinorTickSpacing(9);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("уровень сложности");
        jSlider1.setValue(36);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMoved(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Банзай");

        jButton1.setText("Проверить");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0:00");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t50, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t51, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t52, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t40, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t41, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t42, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t53, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t54, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t55, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t43, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t44, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t45, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(t33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t34, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t56, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t57, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t58, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t46, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t47, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t48, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t00, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t01, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t02, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t03, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t04, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t05, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t06, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t07, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t08, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t60, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t61, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t62, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t80, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t81, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t82, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t70, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t71, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t72, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t63, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t64, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t65, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t83, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t84, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t85, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t73, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t74, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t75, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t66, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t67, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t68, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t86, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t87, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t88, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t76, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t77, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t78, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(butRasklad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butRasklad, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Игра");

        jMenuItem1.setText("Новый расклад");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRasklad(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Проверить");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Показать решение");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResh(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Сервис");

        jSound.setSelected(true);
        jSound.setText("Звук");
        jSound.setToolTipText("");
        jSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoundActionPerformed(evt);
            }
        });
        jMenu3.add(jSound);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Инфо");
        jMenu2.setToolTipText("");

        jMenuItem3.setText("Цель игры");
        jMenuItem3.setToolTipText("");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Доска почета");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Об авторе");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tableFill();
        timer.schedule(timeCount, 0, 1000);
        music();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butRaskladListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRaskladListener
        tableFill();
    }//GEN-LAST:event_butRaskladListener

    private void showResh(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResh
        reshenie();
    }//GEN-LAST:event_showResh

    private void newRasklad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRasklad
        tableFill();
    }//GEN-LAST:event_newRasklad

    private void sliderMoved(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMoved
        int a=jSlider1.getValue();
        switch (a)
        {
            case 63:
            {jLabel1.setText("Камикадзе");
            difficulty="Камикадзе";
            tableFill();
            break;}
            case 54:
            {jLabel1.setText("Самурай");
            difficulty="Самурай";
            tableFill();
            break;}
            case 45:
            {jLabel1.setText("Сенсэй");
            difficulty="Сенсэй";
            tableFill();
            break;}
            case 36:
            {jLabel1.setText("Банзай");
            difficulty="Банзай";
            tableFill();
            break;}
            case 27:
            {jLabel1.setText("Ученик");
            difficulty="Ученик";
            tableFill();
            break;}
        }
    }//GEN-LAST:event_sliderMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        proverka();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(this, "Заполнить все свободные поля \n"
                                          + "числами от 1 до 9 так, чтобы \n"
                                          + "в каждой строке, в каждом столбце \n"
                                          + "и в каждом малом квадрате 3×3 \n"
                                          + "каждая цифра встречалась бы \n"
                                          + "только один раз..","Цель игры Судоку",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        proverka();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        hof();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDifficultyActionPerformed
        switch(jDifficulty.getSelectedIndex()){
        case 0:
        {
          jSlider1.setValue(27);
          break;}
        case 1:
        {
          jSlider1.setValue(36);
          break;}
        case 2:
        {
          jSlider1.setValue(45);
          break;}
        case 3:
        {
          jSlider1.setValue(54);
          break;}
        case 4:
        {
          jSlider1.setValue(63);
          break;}
    }      
    hof();
    }//GEN-LAST:event_jDifficultyActionPerformed

    private void jSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoundActionPerformed
        if (jSound.isSelected()){
            music();
        }else MGP.stop(BGM);
    }//GEN-LAST:event_jSoundActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       JOptionPane.showMessageDialog(this, "Автор: Даулет Кшибеков"
                                          ,"Об авторе",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Frame().setVisible(true);
                           
            }
        });
       
       
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butRasklad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jDifficulty;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JCheckBoxMenuItem jSound;
    private javax.swing.JTextArea jText;
    private javax.swing.JTextField t00;
    private javax.swing.JTextField t01;
    private javax.swing.JTextField t02;
    private javax.swing.JTextField t03;
    private javax.swing.JTextField t04;
    private javax.swing.JTextField t05;
    private javax.swing.JTextField t06;
    private javax.swing.JTextField t07;
    private javax.swing.JTextField t08;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t24;
    private javax.swing.JTextField t25;
    private javax.swing.JTextField t26;
    private javax.swing.JTextField t27;
    private javax.swing.JTextField t28;
    private javax.swing.JTextField t30;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField t33;
    private javax.swing.JTextField t34;
    private javax.swing.JTextField t35;
    private javax.swing.JTextField t36;
    private javax.swing.JTextField t37;
    private javax.swing.JTextField t38;
    private javax.swing.JTextField t40;
    private javax.swing.JTextField t41;
    private javax.swing.JTextField t42;
    private javax.swing.JTextField t43;
    private javax.swing.JTextField t44;
    private javax.swing.JTextField t45;
    private javax.swing.JTextField t46;
    private javax.swing.JTextField t47;
    private javax.swing.JTextField t48;
    private javax.swing.JTextField t50;
    private javax.swing.JTextField t51;
    private javax.swing.JTextField t52;
    private javax.swing.JTextField t53;
    private javax.swing.JTextField t54;
    private javax.swing.JTextField t55;
    private javax.swing.JTextField t56;
    private javax.swing.JTextField t57;
    private javax.swing.JTextField t58;
    private javax.swing.JTextField t60;
    private javax.swing.JTextField t61;
    private javax.swing.JTextField t62;
    private javax.swing.JTextField t63;
    private javax.swing.JTextField t64;
    private javax.swing.JTextField t65;
    private javax.swing.JTextField t66;
    private javax.swing.JTextField t67;
    private javax.swing.JTextField t68;
    private javax.swing.JTextField t70;
    private javax.swing.JTextField t71;
    private javax.swing.JTextField t72;
    private javax.swing.JTextField t73;
    private javax.swing.JTextField t74;
    private javax.swing.JTextField t75;
    private javax.swing.JTextField t76;
    private javax.swing.JTextField t77;
    private javax.swing.JTextField t78;
    private javax.swing.JTextField t80;
    private javax.swing.JTextField t81;
    private javax.swing.JTextField t82;
    private javax.swing.JTextField t83;
    private javax.swing.JTextField t84;
    private javax.swing.JTextField t85;
    private javax.swing.JTextField t86;
    private javax.swing.JTextField t87;
    private javax.swing.JTextField t88;
    // End of variables declaration//GEN-END:variables

private void tableFill(){
    proverka=0;
    
    switch (jSlider1.getValue())
        {
            case 63:
            {
            difficulty="Камикадзе";
            break;}
            case 54:
            {
            difficulty="Самурай";
            break;}
            case 45:
            {
            difficulty="Сенсэй";
            break;}
            case 36:
            {
            difficulty="Банзай";
            break;}
            case 27:
            {
            difficulty="Ученик";
            break;}
        }
   JTextField[][] tm = {{t00,t01,t02,t03,t04,t05,t06,t07,t08}, {t10,t11,t12,t13,t14,t15,t16,t17,t18}, {t20,t21,t22,t23,t24,t25,t26,t27,t28}, {t30,t31,t32,t33,t34,t35,t36,t37,t38}, {t40,t41,t42,t43,t44,t45,t46,t47,t48}, {t50,t51,t52,t53,t54,t55,t56,t57,t58}, {t60,t61,t62,t63,t64,t65,t66,t67,t68}, {t70,t71,t72,t73,t74,t75,t76,t77,t78}, {t80,t81,t82,t83,t84,t85,t86,t87,t88}}; 
   tm1=tm;
   timecount=0;
   istimerrun=true;
   int[][]s=sudocu.rasclad();
   s1=s;
   
   
   for (int e=0;e<9;e++){
       for (int f=0;f<9;f++){
           tm[e][f].setEditable(true);
           tm[e][f].setBackground(Color.white);
           tm[e][f].setText("");
           tm[e][f].setFont(new java.awt.Font("Tahoma", 0, 11));
           
       }
   }
   int a=(90-jSlider1.getValue());
    
   for (int b=0;b<a;b++){
       int c,d,e;
       do{
           e=1;
       do{
       c=(int)(Math.random()*10);
       d=(int)(Math.random()*10);
       }while (c>8||d>8);
       if (!"".equals(tm[c][d].getText()))e=0;
       }while(e==0);
       tm[c][d].setText(String.valueOf(s[c][d]));
       tm[c][d].setFont(new java.awt.Font("Tahoma", 1, 11));
       tm[c][d].setEditable(false);
   }
}

private void reshenie(){
   //JTextField[][] tm={{t00,t01,t02,t03,t04,t05,t06,t07,t08},{t10,t11,t12,t13,t14,t15,t16,t17,t18},{t20,t21,t22,t23,t24,t25,t26,t27,t28},{t30,t31,t32,t33,t34,t35,t36,t37,t38},{t40,t41,t42,t43,t44,t45,t46,t47,t48},{t50,t51,t52,t53,t54,t55,t56,t57,t58},{t60,t61,t62,t63,t64,t65,t66,t67,t68},{t70,t71,t72,t73,t74,t75,t76,t77,t78},{t80,t81,t82,t83,t84,t85,t86,t87,t88}};           
    proverka=1;
    istimerrun=false;
    for (int n=0;n<9;n++){
            for (int i=0;i<9;i++){
              tm1[n][i].setText(String.valueOf(s1[n][i]));
              tm1[n][i].setEditable(false);
              
            }
            
        }
}

    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    private void proverka() {
        if (proverka==1)return;
        int sudokuerr=0;
        for (int a=0;a<9;a++){
            for (int b=0;b<9;b++){
               if (tm1[a][b].getText().equals("")){
                   JOptionPane.showMessageDialog(this, "Вы не заполнили все поля.","Sudoku",JOptionPane.PLAIN_MESSAGE);
                   return;
               } 
            }
        }
        istimerrun=false;
        for (int a=0;a<9;a++){
            for (int b=0;b<9;b++){
               if (!tm1[a][b].getText().equals(String.valueOf(s1[a][b]))){
                tm1[a][b].setBackground(Color.red);   
                sudokuerr=1;
               } 
            }
        }
        if (sudokuerr==1){
            JOptionPane.showMessageDialog(this, "Извините, но Вы не решили это задание...","Sudoku",JOptionPane.PLAIN_MESSAGE);
            
        }
        else{
            win();
        }
        
    }

    private void win() {
        Icon icon=new ImageIcon("sudoku.png");
        String mes=("Поздравляем! Вы правильно решили это задание...\n Ваше время "+(tk.TimeConverter(timecount)));
        JOptionPane.showMessageDialog(this,mes,"Sudoku",JOptionPane.PLAIN_MESSAGE,icon);
        
        file=new File("hof.rkd");//создали объект файла, но не сам файл
        if (!file.exists()) {try {// если файла еще нет
            file.createNewFile();//создали сам файл 
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
                String winname=winname(icon);
                GregorianCalendar date=new GregorianCalendar();
                
                Winner[][] winners= new Winner[5][5];
                               
         switch (difficulty)
        {
            case "Камикадзе":
            {
                Winner winnerKam=new Winner(difficulty,winname, timecnt, date);
                winners[4][0]=winnerKam;
            break;}
            case "Самурай":
            {
                Winner winnerSam=new Winner(difficulty,winname, timecnt, date);
                winners[3][0]=winnerSam;
            break;}
            case "Сенсэй":
            {
                Winner winnerSen=new Winner(difficulty,winname, timecnt, date);
                winners[2][0]=winnerSen;
            break;}
            case "Банзай":
            {
                Winner winnerBan=new Winner(difficulty,winname, timecnt, date);
                winners[1][0]=winnerBan;
            break;}
            case "Ученик":
            {
                Winner winnerUch=new Winner(difficulty,winname, timecnt, date);
                winners[0][0]=winnerUch;
            break;}
        }
            serialize(winners);
            
      } else//если файл уже существует
        {
           Winner[][] winners=deserialize(); 
            
            switch (difficulty)
        {
            case "Камикадзе":
            {
            recCheck(4,winners,icon);    
            break;}
            case "Самурай":
            {
            recCheck(3,winners,icon);    
            break;}
            case "Сенсэй":
            {
            recCheck(2,winners,icon);    
            break;}
            case "Банзай":
            {
            recCheck(1,winners,icon);    
            break;}
            case "Ученик":
            {
            recCheck(0,winners,icon);    
            break;}
        }
                     
        }
           
    }

    
public class MyTimerTask extends TimerTask{

    @Override
    public void run() {
    if (istimerrun){
      timecount+=1;
      timecnt=timecount;
      jLabel2.setText(tk.TimeConverter(timecount));
  
    }
    }
}


public String winname(Icon icon){
          
    int getname=0;
    String s;
            
    do{
    s = (String)JOptionPane.showInputDialog(
                    this,
                    "Ваше имя, мастер...",
                    "Доска почета Sudoku: новый рекорд!!!",
                    JOptionPane.OK_OPTION,icon,null,null);

    //If a string was returned, say so.
    if ((s != null) && (s.length() > 0)) {
    getname=1;
    }else{
        JOptionPane.showMessageDialog(this, "Не стоит скромничать, страна\n должна знать своих героев!","Sudoku",JOptionPane.PLAIN_MESSAGE,icon);
    }
    
    }while (getname==0);
          
    return s;
    
} 

public void recCheck(int y,Winner[][] winners,Icon icon){
    int mtf=0;//more than five
                  for (int i=0;i<5;i++){
                    if (winners[y][i]==null){// если первые 5 мест еще не заняты
                        mtf=1;
                        String winname=winname(icon);
                        GregorianCalendar date=new GregorianCalendar();
                        Winner winnerKam=new Winner(difficulty,winname, timecnt, date);
                        winners[y][i]=winnerKam;
                        serialize(winners);
                        break;
                    }
                  }
    
                    if (mtf==0){// если первые 5 мест уже заняты
                        
                        int maxcnt=winners[y][0].getTimecnt();
                        for (int z=1;z<5;z++){//заполняем массив существующими рекордами
                           if (winners[y][z].getTimecnt()>maxcnt) maxcnt=winners[y][z].getTimecnt();
                        }
                        if (timecnt<maxcnt){
                            String winname=winname(icon);
                            GregorianCalendar date=new GregorianCalendar();
                            for (int x=0;x<5;x++){
                                if (winners[y][x].getTimecnt()==maxcnt) {
                                    winners[y][x].setDifficulty(difficulty);
                                    winners[y][x].setName(winname);
                                    winners[y][x].setTimecnt(timecnt);
                                    winners[y][x].setDate(date);
                                    serialize(winners);
                                    break;
                                }                           
                            }
                        }
                }
}

public Winner[][] deserialize(){
    Winner[][] winners = null;
    file=new File("hof.rkd");
    if (!file.exists()){
         return null;
    }else{
    try {
            FileInputStream fis = new FileInputStream(file);
            ObjectInputStream oin = new ObjectInputStream(fis);
            winners = (Winner[][]) (Object) oin.readObject();
            fis.close();
            oin.close();
            return winners;
            } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
          return winners;
    }      
}

public void serialize(Winner[][] winners){
    file=new File("hof.rkd");
    try {
            FileOutputStream fos = new FileOutputStream(file,false);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(winners);
            oos.flush();
            oos.close();
            fos.close();
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    hof();
}

public void hof(){
    jFrame1.setVisible(true);
    jFrame1.setLocationRelativeTo(null);
    jFrame1.setIconImage(new ImageIcon("sudoku.png").getImage());
    Winner[][] winners=deserialize();
    
    if (winners==null){
        JOptionPane.showMessageDialog(this,"Извините, но на доске почета пока никого нет.","Sudoku",JOptionPane.PLAIN_MESSAGE);
        return;
    }
    
    int i=0;
    
    int a=jSlider1.getValue();
        switch (a)
        {
            case 63:
            {jLabel1.setText("Камикадзе");
            difficulty="Камикадзе";
            jDifficulty.setSelectedIndex(4); 
            i=4;
            break;}
            case 54:
            {jLabel1.setText("Самурай");
            difficulty="Самурай";
            jDifficulty.setSelectedIndex(3); 
            i=3;
            break;}
            case 45:
            {jLabel1.setText("Сенсэй");
            difficulty="Сенсэй";
            jDifficulty.setSelectedIndex(2);
            i=2;
            break;}
            case 36:
            {jLabel1.setText("Банзай");
            difficulty="Банзай";
            jDifficulty.setSelectedIndex(1);
            i=1;
            break;}
            case 27:
            {jLabel1.setText("Ученик");
            difficulty="Ученик";
            jDifficulty.setSelectedIndex(0); 
            i=0;
            break;}
        }
        
    if (winners[i][0]==null){
        jText.setText("");
              JOptionPane.showMessageDialog(this,"Извините, но в категории "+difficulty
                                                +"\n на доске почета пока никого нет.","Sudoku",JOptionPane.PLAIN_MESSAGE);
              return;
    }
    
    int[] win=new int[5]; // сюда запишем рекорды (время) 
    Winner[] winn=new Winner[5];
    int f1=0;
    
    try{
    for (int f=0;f<5;f++){
       if (winners[i][f]!=null) {
           win[f]=winners[i][f].getTimecnt();
       }else {
           break;
       }
        
    }
    Arrays.sort(win); // сортируем рекорды по возрастанию
    
    for (int f=0;f<5;f++){ // перепишем рекордсменов в массив winn в соответствии с сортировкой в win 
        for(int b=0;b<5;b++){
            if(winners[i][b]!=null){
                if (winners[i][b].getTimecnt()==win[f]){
                    if (f1<5)winn[f1]=winners[i][b];
                    f1+=1;
                }
            }
        }
    }

    String text=("1. "+winn[0].getName()+"   результат: "+tk.TimeConverter(winn[0].getTimecnt())+"   дата и время: "+(winn[0].getDate()).getTime());
    int num=2;
    for (int j=1;j<5;j++){
        if(winn[j]!=null){
        text=(text+("\n"+num+". "+winn[j].getName()+"   результат: "+tk.TimeConverter(winn[j].getTimecnt()))+"   дата и время: "+(winn[j].getDate()).getTime());
        num+=1;
        } else {
            break;
        }
    }
    jText.setText(text);
    }
    catch (Exception e) {
      Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, e);      
        }
    }
public void music() 
    {       
        

        ContinuousAudioDataStream loop = null;

        try
        {
            InputStream test = new FileInputStream("sudocu.wav");
            BGM = new AudioStream(test);
            AudioPlayer.player.start(BGM);
            MD = BGM.getData();
            loop = new ContinuousAudioDataStream(MD);

        }
        catch(FileNotFoundException e){
        }
        catch(IOException er)
        {            
        }
        MGP.start(loop);
    }
}


